version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    parameters:
      version:
        description: NodeJS version
        type: string
    executor:
      name: node/default
      tag: << parameters.version >>
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - repo-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: repo-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn run test
      - run: yarn run coveralls
      - run: yarn run lint
  

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["15.10.0", "13.14.0", "10.24.0"]
